[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_complete_delay = 0
    let g:deoplete#auto_complete_start_length = 1
    set completeopt-=preview
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
dpends = 'deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
dpends = 'neosnippet.nvim'
